### ISSUE TITLE
List of known working wifi dongles

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/docs#142]
We need a page that lists know working and problematic wifi dongles, so we can recommend them to users.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_lpp)

**Comment by imrehg** [comment]
Add 2.4/5GHz dongles, and have internal advice on how to choose a dongle that works.

**Comment by zwalchuk** [comment]
Done: https://docs.resin.io/hardware/wifi-dongles/
