### ISSUE TITLE
Error message on Pi: 7 short blinks

### ISSUE THREAD

**Issue by filippoferraris** [resin-io/docs#144]
On a Raspberry Pi I receive 7 short blinks from the 'ACT' LED. What does it mean?

Probably someone should add this error to the documentation page! Thanks!
http://docs.resin.io/#/pages/troubleshooting/error.md

**Comment by filippoferraris** [comment]
realised it's the Pi error blink message:
http://elinux.org/R-Pi_Troubleshooting#Green_LED_blinks_in_a_specific_pattern

**Comment by emirotin** [comment]
I think it's still valid to mention it / put as link in our docs.

**Comment by shaunmulligan** [comment]
This is now mentioned in our FAQ troubleshooting section: https://github.com/resin-io/docs/pull/231/
