### ISSUE TITLE
'Montserrat' font is not loaded

### ISSUE THREAD

**Issue by emirotin** [resin-io/docs#166]
The recent change breaks the headers because the Montserrat webfont is not loaded.

**Comment by taahirisaacs** [comment]
@emirotin Will amend thanks for the catch

**Comment by emirotin** [comment]
I can fix it, no worries

**Comment by taahirisaacs** [comment]
@emirotin thanks here's the link for reference:

<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
