### ISSUE TITLE
update docs on using the webterminal

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/docs#198]

**Comment by emirotin** [comment]
JFYI: we'll migrate from `gh-pages` to `master` as out main branch soon.
But it actually has no implications as long as you edit `.md` files and images only.
There will be a moment this week when I will switch the default branch, then merge all recent changes from `gh-pages` to `master` and then delete / archive the `gh-pages` branch.

**Comment by shaunmulligan** [comment]
fixed in https://github.com/resin-io/docs/pull/199
