### ISSUE TITLE
Document all the RESIN_SUPERVISOR_ env vars available

### ISSUE THREAD

**Issue by Page-** [resin-io/docs#201]
Rather than having them spread across various blog entries:
https://resin.io/blog/device-bandwidthdata-usage-how-low-can-we-go/
https://resin.io/blog/updating-config-txt-remotely/
https://resin.io/blog/customize-the-way-your-devices-are-updated/

**Comment by Page-** [comment]
https://github.com/resin-io/resin-supervisor/issues/87

**Comment by zwalchuk** [comment]
fixed in #702

**Comment by zwalchuk** [comment]
Current config variables documented here: https://docs.resin.io/learn/manage/configuration/
