### ISSUE TITLE
Intra-page navigation links auto-scroll past the target title

### ISSUE THREAD

**Issue by petrosagg** [resin-io/docs#224]
## How to reproduce

Visit http://docs.resin.io/runtime/runtime/#device-urls
## Expected behaviour

The page should scroll and the "Device URLs" title should be at the top of the window
## Actual behaviour

The page will scroll past the "Device URLs" title.
![foo](https://cloud.githubusercontent.com/assets/939420/15136401/516e5084-1636-11e6-9db7-0853a5c95c3d.png)

**Comment by emirotin** [comment]
That's because of the sticky header unfortunately. I actually question if we need it — what's the value of sticky breadcrumbs?
