### ISSUE TITLE
edison: update instructions on using `brew install` to install flash tools

### ISSUE THREAD

**Issue by lekkas** [resin-io/docs#241]
The guide on http://docs.resin.io/installing/gettingStarted-Edison/#dfu-util-on-mac-osx advises against using `brew install` to install `dfu-utils` . However the latest official guide uses it and at least in El Capital it seems to work.

The OS X version were I successfully flashed a resin image on edison using brew is `El Capital 10.11.4`.
The installed brew version is `0.9`

**Comment by zwalchuk** [comment]
We don't have these instructions anymore, closing.
