### ISSUE TITLE
Make images wiki more discoverable

### ISSUE THREAD

**Issue by lorenzo-stoakes** [resin-io/docs#248]
A very usual workflow for me is to look up the [resin images wiki](http://docs.resin.io/runtime/resin-base-images/) in order to work out what the correct base image to use should be.

However, this page doesn't seem hugely discoverable - for one, I think it'd be useful for 'base' to be in title (I think this was changed) as 'base image' is the usual nomenclature for these images, I was confused when the name was first changed and was thrown a bit.

For another, the page isn't linked on the front page, or on the Reference tab (I _really_ think it should be there), and takes a bit of tracking down.

I imagine many users still simply browse our Dockerhub page and try to find a base image that seems to logically fit the device they're using, which often might lead to sub-optimal choices (for example getting a raw armv7hf image then installing node on top) - I think we should be singing about this page from the rooftops!

**Comment by lurch** [comment]
Given that the associated #249 has been merged, should this be closed?

**Comment by emirotin** [comment]
I think so
