### ISSUE TITLE
Document UART usage on RPI3

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/docs#265]
There seems to be difficulties for users getting this right, we need proper documentation on how to use it.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/inboxes/topics/24925)

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_j8d)

**Comment by imrehg** [comment]
This and a bunch of other RPi hardware guidance would be very timely. For example there's a lot of BLE question too, that is non-obvious. The best would be probably to add an RPi "cookbook" or "tips & tricks" section or page.

**Comment by imrehg** [comment]
Add also `RESIN_HOST_CONFIG_dtoverlay` usage with `pi3-miniuart-bt-overlay`.

**Comment by shaunmulligan** [comment]
to enable uart on RPI3:

RESIN_HOST_CONFIG_core_freq = 250

RESIN_HOST_CONFIG_dtoveraly=pi3-disable-bt

RESIN_HOST_CONFIG_enable_uart=1
