### ISSUE TITLE
Supervisor API docs no longer contain info about update locking

### ISSUE THREAD

**Issue by Page-** [resin-io/docs#273]
http://docs.resin.io/runtime/supervisor-api/#update-locking is missing - and there's a broken link from http://docs.resin.io/management/devices/#update-locking pointing to it

**Comment by imrehg** [comment]
Looks like it got removed in 5a802d8ec63e098909561b37adc805309b955b72#diff-5408e175931cda52d29182c8c5b2028a by @craig-mulligan, related to #168 . Looks like maybe a side-effect? Will investigate and put it back (somewhere, with fixed reference)

**Comment by Page-** [comment]
cc @pcarranzav

**Comment by shaunmulligan** [comment]
connects to #280
