### ISSUE TITLE
Document Timezone and how time can be set in runtime

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/docs#283]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_jx6)

**Comment by imrehg** [comment]
Great point!
Some difficulty figuring that out was that all 3 systems we run do things somewhat different, and that `timedatectl` does not quite work for some reason which would tie things together easier. IMHO needs a bit more research, but should be in there for sure!
