### ISSUE TITLE
Dockerfile deployment guide should mention `.templates`

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/docs#284]
We should mention `Dockerfile.template` in the deployment guide and speak specifically about the order of preference in the builder, namely:
`Dockerfile.template` -> `Dockerfile` -> `package.json`

**Comment by zwalchuk** [comment]
We have a [Dockerfile template page](https://docs.resin.io/deployment/docker-templates/), but it is not linked to in the Dockerfile guide. Should probably just be incorporated into that page

**Comment by zwalchuk** [comment]
duplicate of #290
