### ISSUE TITLE
Note that RPI3 can't connect to 5GHz wifi

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/docs#302]
The hardware on rpi3 only supports 2.4GHz connections.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ksl)

**Comment by zwalchuk** [comment]
Shown in dashboard when downloading image
