### ISSUE TITLE
Importance of sync after writing stuff to /data

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/docs#311]
sometimes user restart or reboot and notice that their data is not actually persisted in /data. usually they have not run `sync` beforehand.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_lei)

**Comment by zwalchuk** [comment]
duplicate of #197
