### ISSUE TITLE
Using env vars in custom ssh sessions

### ISSUE THREAD

**Issue by imrehg** [resin-io/docs#318]
In case someone logs in to the device though their own-run SSH, and need the resin-specific env vars.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_lpn)

**Comment by zwalchuk** [comment]
Documented here: https://docs.resin.io/runtime/runtime/#using-resin-ssh-from-the-cli
