### ISSUE TITLE
The `modprobe` command to enable the camera on the Raspberry Pi is out of date. 

### ISSUE THREAD

**Issue by josephroberts** [resin-io/docs#326]
`modprobe bcm2835-v4l2` returns an error and should be replaced with `modprobe v4l2_common` in this section https://docs.resin.io/hardware/i2c-and-spi/#raspberry-pi-camera-module

**Comment by imrehg** [comment]
Thanks @josephroberts, it is out of date indeed.

I think there are other issues as well, eg. for me to enable the camera, the only thing needed was `start_x=1` in the config (or `RESIN_HOST_CONFIG_start_x` set to `1`), and didn't require any modprobe. Will need to check a bit to give the proper, up to date solution. (And I guess the demo projects need some updating too:)

**Comment by lurch** [comment]
This could be closed now #352 has been merged? Or is this pending on a push-to-production?

**Comment by imrehg** [comment]
Still seems to need to cross-check a couple of things.

**Comment by emirotin** [comment]
I played with it yesterday and it seems to work with bcm2835-v4l2 as well. @curcuz also says that no modprobe is strictly required

**Comment by imrehg** [comment]
@emirotin yeah, I don't think there's modprobe now, that's why it's not in the docs either. :)

**Comment by lurch** [comment]
https://github.com/resin-io/docs/pull/352#issuecomment-257613869 ;-)
