### ISSUE TITLE
Write about Fleet/Device configuration explicitly

### ISSUE THREAD

**Issue by imrehg** [resin-io/docs#338]
The current [Environment Variables page](https://docs.resin.io/management/env-vars/) just mention env vars, and don't see (or can't find) any info on Fleet/Device configuration, and the difference between that and env vars. This is confusing for people (see [gitter chat](https://gitter.im/resin-io/chat?at=57ee35d70ff4ef7a50f250b5). It should be explicitly described.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_sec)

**Comment by joeyvandijk** [comment]
Just mention a warning that someone puts a RESIN_ variable inside a place that it should not be in.

**Comment by imrehg** [comment]
@joeyvandijk that's the job of the resin dashboard UI, that's being checked. Still it should be documented, so people can know the behaviour without warnings. :)

**Comment by zwalchuk** [comment]
Fixed by #702

**Comment by zwalchuk** [comment]
Current config variables documented here: https://docs.resin.io/learn/manage/configuration/
