### ISSUE TITLE
document the moving of config.json to the boot partition

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/docs#357]
The config.json has been moved from /resin-conf/config.json to /resin-boot/config.json. This has been since resinOS 1.2+

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ra9)

**Comment by imrehg** [comment]
@shaunmulligan is this still pending, or can be closed? as there's a merged update for it.
