### ISSUE TITLE
Docs Structure Proposal

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/docs#360]
# docs
* Learn
  * Welcome to Resin.io
  * Getting started with `<language>` on `<device>`
    * Introduction
    * Using support
    * What you'll learn
    * What you'll need
    * Basic concepts
    * Provisioning your device
    * Getting resinOS
    * Selecting Network Configuration
    * Creating the boot Device
    * Getting the device on the Dashboard
    * Pushing code to your device
    * clone the example
    * add the resin application remote
    * Push and build
    * Using the terminal
    * Using resin-sync to develop fast
    * Setting up the resin CLI
    * Syncing to /usr/src/app
    * How to use resin-sync.yml
    * Example projects to get started with (boilerplate for `<language>`, `<device>`, `<use case>`)
  * Resin.io Basics
    * Resin.io Concepts
      * Applications
      * Containers
      * resin remote 
      * Device Agent or Supervisor
      * resinOS the hostOS
      * Build/Run distinction
      * "The builder"
      * dockerfile templates
      * pure node.js projects
      * deviceURL
    * Deployment guide
      * Dockerfile
      * Picking the right base image
    * Development Guide
      * resin sync
        * setup resin sync
        *setup cross compilation for `<language>`
        *using resin sync
      * resin ssh
    * Application Lifecycle
    * Runtime Environment `<base image specific>`
      * init system
        * systemd
        * openrc
      * webterminal
      * writing to dashboard logs
      * Exposed Ports
      * Accessing Env Vars
      * Device URLS
      * Persistent Data Volume
      * interacting with the supervisor
        * this needs to be version specific, how (??)
      * using hostOS DBUS
    * Accessing the `<device>`'s hardware with `<language>`
      * GPIO
      * I2C
      * SPI
      * UART
      * Bluetooth
      * Others (??)
        * CSI camera
        * USB webcam
        * LCD
        * Servo Motor
        * Other radios (??)
    * Management
      * Environment Variables
        * Fleet wide
        * Per Device
      * Configuration
        * Fleet wide
        * Per Device
      * Actions
        * Fleet wide
        * Per Device
      * Build Logs
      * Fleet Location
      * Account management
        * Account Details
        * SSH keys
        * Profile
        * 2FA
        * Collaborators
    * Using the resin-cli
    * Resin Device Agent
        * Deltas
        * Locks
        * special env vars
          * update strategies
          * bandwidth
          * restart policies
          * misc
        * supervisor API
    * Network Setup
        * Wifi config
        * Cell connectivity
        * Static IP
    * Integrating with third party services
    * Team Collaboration
    * Troubleshooting (Basic)
  * Advanced development with resin.io
    * Converting your `<language>` project to a Dockerfile
    * Optimizing builds
    * Dockerfile Templates
    * Advanced Device Configuration
      * Delta Updates
      * Host OS Config `<device-type>`
        * config.txt `<raspberrypi>`
        * cmdline.txt
        * uEnv.txt
      * Update locking 
      * Update strategies
      * Bandwidth Reduction
    * Adding custom device support for Resin OS
    * Contributing to Resin.io
    * Troubleshooting (advanced)
    * Microcontrollers [TBD]
    * Custom DTB [TBD]
    * Custom Kernel modules [TBD]
  * Moving to production with resin.io
    * Preloaded Application Containers
    * Canary Rollouts
    * Bandwidth Optimisation
    * Activating the Watchdog(s)
    * Pinning dependency versions
    * Troubleshooting in production
* FAQ
* Reference
  * What's in the Resin host OS (also version specific??)
    * kernel info
    * disk partitioning info
    * file system
    * network management system
    * configuration
      * how to add stuff in boot config, etc
  * Supported Devices & Hardware
    * SBCs
    * peripheral devices
    * wifi adapters
    * cellular modems [TBD]
  * Server API
  * Agent/Supervisor API
  * SDK
  * Node.js
  * Python
  * CLI

**Comment by shaunmulligan** [comment]
@imrehg this was the docs structure I was talking about the other day ^^

**Comment by imrehg** [comment]
Cheers, very handy!

**Comment by shaunmulligan** [comment]
@imrehg don't take it as gospel, it needs some debate and discussion, because there is a lot of repetition between sections and there may be better logical groupings, this is just a proposal. The one think that having this highlights is how much is missing from the current docs

**Comment by zwalchuk** [comment]
Moved to spec: https://github.com/resin-io/hq/blob/docs-restructure/specs/docs-restructure-plan.md
