### ISSUE TITLE
Update repo description

### ISSUE THREAD

**Issue by lurch** [resin-io/docs#361]
Similarly to https://github.com/resin-io/etcher-homepage/issues/21 , I guess it might be handy if this repo's description was updated to include https://docs.resin.io/ ?

**Comment by imrehg** [comment]
@shaunmulligan (or could we add more people to be able to adjust the repo params)

**Comment by shaunmulligan** [comment]
@lurch I added the docs link to the description, good to close?

**Comment by lurch** [comment]
Thanks.
