### ISSUE TITLE
Rust getting start guide on rpi1 incorrectly warns about base image

### ISSUE THREAD

**Issue by wrboyce** [resin-io/docs#383]
The warning:

> Warning: If you deploy this code to a Raspberry Pi V1 or ZERO, then you will need to change the -debian suffix to -raspbian since there is no Debian base image for these device types.

is contrary to the images wiki, and not (no longer?) true.

[link](https://docs.resin.io/raspberrypi/rust/getting-started/#let-s-dive-into-the-code)

**Comment by emirotin** [comment]
Yeah, a "fake" `resin/raspberrypi-debian` was created that is actually raspbian.
Try fixing it yourself and sending a PR :)
