### ISSUE TITLE
Docs are periodically slow to load

### ISSUE THREAD

**Issue by alisondavis17** [resin-io/docs#481]
Behavior noticed by myself, @jviotti, and a user survey response

Per @jviotti:

"As far as I’ve seen, the HTTP requests for the external resources linked from the HTML are the ones that timeout. So the main HTML page arrives just fine, but the CSS/JS/images linked from there hang"

**Comment by emirotin** [comment]
A quick look reveals we have lots of uncombined CSS and JS files, and some external requests, like google fonts. The low-hanging fruit here is combining the assets, and replacing the google fonts with our own hosted version
