### ISSUE TITLE
host OS ssh access clarifications

### ISSUE THREAD

**Issue by agherzan** [resin-io/docs#491]
People are asking if they have access to host OS in production? We should clarify this in our documentation if not already done.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1k33)

**Comment by zwalchuk** [comment]
Already documented: https://docs.resin.io/understanding/understanding-devices/2.0.0/#dev-vs-prod-images
