### ISSUE TITLE
Document recommending production peripheral

### ISSUE THREAD

**Issue by sonyagreen** [resin-io/docs#519]
Similar to the issue asking to [recommend SD cards](https://github.com/resin-io/docs/issues/297), giving users info on what board+resin+peripheral works well (like wifi dongle).

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1t29)

**Comment by shaunmulligan** [comment]
I think this is a bit to broad. We can do wifi, by there are millions of peripherals that are possible and we wouldn't do a good job of covering it. There is this issue for wifi: https://github.com/resin-io/docs/issues/142

**Comment by sonyagreen** [comment]
I went broad with the assumption that this would accumulate the different types of peripherals we'd customers ask through (via support). I'll attach the Front ticket to #142.
