### ISSUE TITLE
Instructions for changing reg domain of wifi via config.json

### ISSUE THREAD

**Issue by zwalchuk** [resin-io/docs#523]
Connects to https://github.com/resin-os/resinos/issues/309 and https://github.com/resin-os/meta-resin/pull/681

**Comment by Jbithell** [comment]
In the meantime https://github.com/resin-os/meta-resin/pull/681#issuecomment-303935513 is very helpful

**Comment by floion** [comment]
Yes @Jbithell , this is released in resinOS v2.0.6+rev1 for the raspberrypi 3 so you can give it a go

**Comment by zwalchuk** [comment]
Updates complete: https://docs.resin.io/deployment/network/2.0.0/#regulatory-domain

**Comment by Jbithell** [comment]
Should also correct: https://docs.resin.io/troubleshooting/troubleshooting/#raspberry-pi

> **Wifi connection problems on RPI3**
> If you are having issues with your RPI3 connecting to your wifi, make sure to check that the 2.4 GHz channel on your wifi router is set to something less than 11, since the firmware on the Raspberry Pi doesn't support channel 12 and 13.
