### ISSUE TITLE
Broken link in http://docs.resin.io/#/pages/installing/gettingStarted.md

### ISSUE THREAD

**Issue by DeeJay** [resin-io/docs#53]
In the document http://docs.resin.io/#/pages/installing/gettingStarted.md

Immediately preceding the heading http://docs.resin.io/#/pages/installing/gettingStarted.md#further-reading

"Have a look at how to use dockerfiles and play around with our python example..."

embedded link from _dockerfiles_ leads to http://docs.resin.io/#/pages/pages/using/dockerfile.md

Should be: http://docs.resin.io/#/pages/using/dockerfile.md

**Comment by emirotin** [comment]
Thank you for reporting, will fix now. Also you can send docs PRs right from the site using the Improve this Doc button (http://monosnap.com/image/OvPpQEm2l0g0njmxc9dYzHDhV99Zmz.png)
