### ISSUE TITLE
Docs don't mention how to get local logs from host OS

### ISSUE THREAD

**Issue by hedss** [resin-io/docs#531]
In a recent customer interaction a user wanted to be able to retrieve the logs for their device whilst not connected via network but via local terminal.

The recommendation is to use `journalctl` to retrieve the host logs, which allowed them to retrieve the ID for the app container to allow them to finally retrieve the app logs.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1y21)

**Comment by shaunmulligan** [comment]
These instructions only work if the user has direct console access to the device (i.e. it is a `.dev` device) otherwise a resin support engineer has to pull logs for them. This will be solved once @wrboyce implements "leech"/diagnostics action from the dashboard.

**Comment by zwalchuk** [comment]
possible now with Host OS SSH access. This will be fixed when I transfer the info from the Host OS troubleshooting tips blog to the docs

**Comment by zwalchuk** [comment]
Fixed in #724

**Comment by zwalchuk** [comment]
Documented here: https://docs.resin.io/learn/manage/ssh-access/#troubleshooting-with-host-os-access
