### ISSUE TITLE
Getting started links for Jetson TX2, Chip board, Rushup kitra520, Intel NUC, Variscite DART 6UL, Nitrogen 6x, Hummingboard

### ISSUE THREAD

**Issue by floion** [resin-io/docs#534]
https://github.com/resin-os/resin-chip

https://github.com/resin-os/resin-jetson-tx2

https://github.com/resin-os/resin-artik/blob/master/kitra520.coffee

https://github.com/resin-os/resin-intel

https://github.com/resin-os/resin-imx6ul-var-dart

https://github.com/resin-os/resin-fsl-arm/blob/master/nitrogen6x.coffee

https://github.com/resin-os/resin-fsl-arm/blob/master/solidrun-imx6.coffee

**Comment by floion** [comment]
@zwalchuk maybe you can commit a PR in these repositories with these getting started links when they are available please?

**Comment by zwalchuk** [comment]
@floion Sure thing. I need a "What you will need" section for the Chip, TX2, and Dart. Here's the one for the Rpi3, can you help me figure out what differences each of those boards have (or tell me who would be the person most familiar with the devices)? The rest of the guide is pretty similar across boards

- A Raspberry Pi 3 model B. See our supported devices list for other boards.
- A 4GB or larger microSD card. The speed class of the card also matters - class 10 card or above is the way to go.
- [Optional] An ethernet cable
- A micro USB cable.
- [Optional] A 2A USB micro power supply.
- A resin.io account.

**Comment by floion** [comment]
@telphan , please supply this for the TX2
@michal-mazurek please supply this for the CHIP

**Comment by floion** [comment]
As for the Dartboard, @zwalchuk :

A Variscite Dartboard 6UL along with the baseboard that allows flashing from the SD card. See our supported devices list for other boards.
A 4GB or larger microSD card. The speed class of the card also matters - class 10 card or above is the way to go.
An ethernet cable.
Compatible power supply.
A resin.io account.

**Comment by floion** [comment]
Also added to the list https://github.com/resin-os/resin-fsl-arm/blob/master/nitrogen6x.coffee
By the way, do you use the slug name when you create the doc link for a particular board? Or what do you use?

**Comment by floion** [comment]
Also added Hummingboard: https://github.com/resin-os/resin-fsl-arm/blob/master/solidrun-imx6.coffee
