### ISSUE TITLE
"Improve this Doc" links don't work on parametric pages

### ISSUE THREAD

**Issue by zwalchuk** [resin-io/docs#563]
The URL generated on the "Improve this Docs" links is incorrect for any of the parametric pages. The links created for those buttons preface the file with the DOCS_SOURCE_DIR ('pages'), but for the pages that are selected with the dropdown, 'pages' isn't used (for example https://docs.resin.io/deployment/network/2.0.0/)

**Comment by cron410** [comment]
+1

**Comment by lurch** [comment]
Just as an FYI, this also breaks for https://docs.resin.io/understanding/understanding-devices/2.x/
