### ISSUE TITLE
document resin.io provisioning mechanim and key exchange

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/docs#564]
What is the flow of this mechanism, what is the config.json, what is a provision key versus a device API key and the security implications of each.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2661)

**Comment by zwalchuk** [comment]
On security page: https://docs.resin.io/security/#device-access
