### ISSUE TITLE
"IMPROVE THIS DOC" button doesn't work

### ISSUE THREAD

**Issue by Temeteron** [resin-io/docs#566]
The button "improve this doc" doesn't work on some tutorials. When you click it, 404 is caused.

For example, on the [tutorial](https://docs.resin.io/raspberrypi3/nodejs/getting-started/), the button redirects you [here](https://github.com/resin-io/docs/edit/master/pages/raspberrypi3/nodejs/getting-started.md), which is 404.

**Comment by shaunmulligan** [comment]
Thanks for the report, there is an issue tracking that here: https://github.com/resin-io/docs/issues/563 , so I will close this one.
