### ISSUE TITLE
Document hiding the "Check your resin.io dashboard message.

### ISSUE THREAD

**Issue by imrehg** [resin-io/docs#588]
That's done by `RESIN_HOST_LOG_TO_DISPLAY` set to 0 on 1.x devices, and should be disabled by default on production images on 2.x.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2coj)

**Comment by zwalchuk** [comment]
Fixed in #724
