### ISSUE TITLE
IMPROVE THIS DOC gives 404

### ISSUE THREAD

**Issue by cron410** [resin-io/docs#594]
https://docs.resin.io/nuc/nodejs/getting-started/

![image](https://user-images.githubusercontent.com/3082899/30875313-202f6544-a2c1-11e7-9ba8-d687cde109d6.png)

https://github.com/resin-io/docs/edit/master/pages/nuc/nodejs/getting-started.md

**Comment by zwalchuk** [comment]
Duplicate of #563
