### ISSUE TITLE
User expects production URLs and consistent branding in screenshots

### ISSUE THREAD

**Issue by sonyagreen** [resin-io/docs#608]
The [current screenshot](https://docs.resin.io/img/common/pushing/success_unicorn_simple_nodejs.png) in the [getting started guide](https://docs.resin.io/raspberrypi3/nodejs/getting-started/#deploying-code) includes a staging URL and a personal account. 🎅 👶 🚂

**Comment by zwalchuk** [comment]
fixed with MC release
