### ISSUE TITLE
Document that Docker metadata may get corrupted if a power off happens right after a container is stopped

### ISSUE THREAD

**Issue by jviotti** [resin-io/docs#616]
See https://app.frontapp.com/open/cnv_a8jvip

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_4t2p)

**Comment by shaunmulligan** [comment]
This seems like something we should fix because it sounds pretty bad. It doesn't help much to document it if the user can't fix it themselves or do anything about it
