### ISSUE TITLE
modprobe and i2c

### ISSUE THREAD

**Issue by orbsmiv** [resin-io/docs#627]
<https://docs.resin.io/hardware/i2c-and-spi/>

`modprobe i2c-dev` doesn't work in a container without mounting the /lib/modules directory from the host system, e.g. adding `-v /lib/modules:/lib/modules` to the _docker run_ command.

Base image: resin/raspberrypi3-python:3.6

**Comment by shaunmulligan** [comment]
Hey @orbsmiv were you using an Unamanged resinOS image from resinos.io? The documentation link you point to is specifically aimed at resin.io platform managed devices which currently have that mount defined by default so modprobe should just work out the box on resin.io. 

On resinOS unmanaged, it is indeed true that you will need to add that volume when starting up your container.

**Comment by zwalchuk** [comment]
docs have been updated for new hardware workflow for multicontainer
