### ISSUE TITLE
Document Host SSH capability

### ISSUE THREAD

**Issue by zwalchuk** [resin-io/docs#652]
Add here: https://docs.resin.io/runtime/runtime/#ssh-access

**Comment by afitzek** [comment]
With the CLI release 6.12.0 we released direct host OS access for our customers.

To use it just add the `--host` or  `-s` option to the ssh command:

For example:

```
resin ssh 7cf02a6 -s
```

This will only work for Resin OS versions >= 2.7.5

The host OS can be used to check on the actual application container, supervisor logs, ...

**Comment by afitzek** [comment]
This will only work when VPN is active and connected.
