### ISSUE TITLE
Update FAQ to reflect recently released host OS SSH access

### ISSUE THREAD

**Issue by alisondavis17** [resin-io/docs#670]
https://docs.resin.io/troubleshooting/faq/#why-can-t-i-ssh-into-or-run-code-in-the-hostos- should be updated to reflect the recently released support for host SSH access on resinOS 2.7.5 and above. 

The "reasons" why we previously did not provide host SSH access should be reframed as "caveats" a user should watch out for when accessing the host.

**Comment by zwalchuk** [comment]
Fixed in #671
