### ISSUE TITLE
Raspberry pi getting started points to deprecated base image

### ISSUE THREAD

**Issue by FRVisser** [resin-io/docs#714]
Hi,

Don't know which file to edit, the [improve this doc](https://github.com/resin-io/docs/edit/master/pages/raspberrypi/python/getting-started.md) button points to a 404. 

However, the raspberry-pi (1) in-combination with `python` [getting started](https://docs.resin.io/raspberrypi/python/getting-started/) doc, refers to the `resin/raspberrypi-python` base image but this should be `resin/raspberry-pi-python`. Since `raspberrypi` is replaced with `raspberry-pi`

Thanks!

**Comment by floion** [comment]
@nghiant2710 is resin/raspberrypi-python deprecated?

**Comment by lurch** [comment]
https://hub.docker.com/r/resin/raspberrypi-python/ says "This repository is obsolete." and https://hub.docker.com/r/resin/raspberry-pi-python/ does indeed appear to be the correct one. The [base-images docs](https://docs.resin.io/runtime/resin-base-images/) also refer to `resin/raspberry-pi-python`.


Hmmm... https://docs.resin.io/runtime/resin-base-images/ has Docker images named like `resin/raspberry-pi-python`, `resin/raspberry-pi2-python` and `resin/raspberrypi3-python` whereas https://docs.resin.io/devicetypes/ lists the "Resin Machine Name"s as `raspberrypi`, `raspberrypi2` and `raspberrypi3`.

https://docs.resin.io/deployment/docker-templates/ also claims the Docker images are named like `resin/raspberrypi-python`, `resin/raspberrypi2-python` and `resin/raspberrypi3-python`, which again conflicts with what https://docs.resin.io/runtime/resin-base-images/ says :confused:

**Comment by shaunmulligan** [comment]
@FRVisser @floion and @lurch yup, its pretty confusing, but this is the following correct base images:
- resin/raspberry-pi-*
- resin/raspberry-pi2-*
- resin/raspberrypi3-*

__Note:__ the RPI3 base image is different from all the others due to some ugly legacy reasons.
