### ISSUE TITLE
Clarify what images can set RESIN_HOST_CONFIG_* env vars

### ISSUE THREAD

**Issue by Shou** [resin-io/docs#725]
User had issues with using `RESIN_HOST_CONFIG_*` env vars (specifically `RESIN_HOST_CONFIG_gpu_mem`) until they realised it's only possible images built by the builder, not `resin local push`ed images.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_8gup)

**Comment by zwalchuk** [comment]
Fixed in #745
