### ISSUE TITLE
Feedback: RESIN_ARCH on Raspberry Pi 3 = armv7hf

### ISSUE THREAD

**Issue by jgentes** [resin-io/docs#729]
I just bought a Pi 3 from Amazon and pushed a resin build to it. The docs say %%RESIN_ARCH%% should = armv8hf but I found it came back as armv7hf during my deployment.

https://github.com/resin-io/docs/blob/master/pages/deployment/docker-templates.md

Just a heads up, not sure if it needs to be updated.

**Comment by shaunmulligan** [comment]
@jgentes it is pretty confusing, but even thought the RPI3 hardware is armv8, none of the operating systems and software for it are armv8 compatible, even the latest raspbian still only comes in armv7hf flavour, perhaps in the future the foundation will start providing armv8 image and at that time so will we, but until then the RPi3 is effectively an armv7hf CPU and software compatible with the RPI2 :)

**Comment by lurch** [comment]
@shaunmulligan Looks like @jgentes is suggesting that https://github.com/resin-io/docs/blob/master/pages/learn/develop/dockerfile.md (which AFAICT is "published" to https://docs.resin.io/deployment/docker-templates/ ) should be updated to say `armv7hf` for the RPi3 instead of `armv8hf` as it does currently?

```
|Raspberry Pi 3|armv8hf|raspberrypi3|[resin/raspberrypi3-debian](https://hub.docker.com/r/resin/raspberrypi3-debian/),  [resin/raspberrypi3-python](https://hub.docker.com/r/resin/raspberrypi3-python/), [resin/raspberrypi3-node](https://hub.docker.com/r/resin/raspberrypi3-node/)||
```

**Comment by jgentes** [comment]
👍 sorry about the dup!
