### ISSUE TITLE
Redirect in place for moved base images page

### ISSUE THREAD

**Issue by imrehg** [resin-io/docs#748]
The base images on Docker Hub have link to our documentation on base images, which is currently broken.

E.g. https://hub.docker.com/r/resin/raspberry-pi-alpine-node/ Full Description links to https://docs.resin.io/runtime/resin-base-images/ but the actual location is now https://docs.resin.io/reference/base-images/resin-base-images/ 

Those descriptions will need to be updated, but likely it would be good to keep continuity with existing links by redirecting `runtime/resin-base-images/` -> `reference/base-images/resin-base-images/`.

**Comment by lurch** [comment]
That's weird, it seems like the former link _is_ now redirecting properly?

**Comment by lurch** [comment]
Ahhh, looks like https://hub.docker.com/r/resin/raspberry-pi-alpine-node/ links to https://docs.resin.io/runtime/resin-base-images/?ref=dockerhub which **doesn't** redirect, but if you remove the query-string then https://docs.resin.io/runtime/resin-base-images/ **does** redirect to https://docs.resin.io/reference/base-images/resin-base-images/

I guess ideally https://docs.resin.io/runtime/resin-base-images/?ref=dockerhub would redirect to https://docs.resin.io/reference/base-images/resin-base-images/?ref=dockerhub ?  (so maybe this is a bug in the redirect-process?)

**Comment by zwalchuk** [comment]
@lurch @imrehg yes, I was just thinking this needed to be fixed more generally, most of the current redirects don't account for things after the page name (i.e. queries and anchor links). Should be an easy fix.
