### ISSUE TITLE
Unrendered links in the Dockerfile page

### ISSUE THREAD

**Issue by majorz** [resin-io/docs#749]
https://docs.resin.io/learn/develop/dockerfile/

Looks like some template issue, but there different unrendered links throughout the page that look like this: `[init system][init-system-link]`.

**Comment by lurch** [comment]
This appears to be a similar problem to https://github.com/resin-os/resinos/pull/441 where somebody added placeholder links, but then forgot to fill in the actual values?

Perhaps there could be a script that runs as part of a CI check that looks for these "undefined links"?

**Comment by majorz** [comment]
Maybe the template rendering engine has such a detection?

**Comment by majorz** [comment]
It detects it, but does its 'thing' like a feature. Boo: https://github.com/markedjs/marked/blob/master/lib/marked.js#L664

I guess a simple grep in the html files for `][` pairs will do the job in the CI.

**Comment by majorz** [comment]
Those are the rendered files that have this kind of problem:
```
[zahari@zahari docs]$ grep -r -l ']\[' contents
contents/learn/develop/dockerfile/index.html
contents/learn/develop/hardware/index.html
contents/learn/develop/hardware/gpio/index.html
contents/learn/more/examples/seed-projects/index.html
contents/learn/more/examples/snippets/index.html
```

**Comment by majorz** [comment]
Ah, and something along those lines can be used to detect issues:
```
[zahari@zahari docs]$ ! grep -r -q ']\[' contents
[zahari@zahari docs]$ echo $?
1
```

**Comment by lurch** [comment]
https://docs.resin.io/learn/develop/hardware/gpio/ doesn't appear to contain any unrendered links?
...ah, upon looking deeper this is because the `][` on that page is within a HTML comment-block ;)

**Comment by majorz** [comment]
Lol

**Comment by majorz** [comment]
You found a secret diagram.

**Comment by lurch** [comment]
What do I win? :)

**Comment by majorz** [comment]
You do.

**Comment by majorz** [comment]
#order [PIKO Cup](http://www.piko-shop.de/index.php?vw_type=artikel&vw_id=8641)
