### ISSUE TITLE
resin-cli: Usage of <short-uuid>.local in the push command does not work

### ISSUE THREAD

**Issue by chibby0ne** [resin-io/docs#836]
The usage of `<short-uuid>.local` in the push command does not work and results
in a error of the type:
```
Push failed. Error: Error while inspecting image local-app: Error: getaddrinfo ENOTFOUND
```
Instead using the IP address or just the `<short-uuid>` works as expected.

I have submitted a PR: #834 to fix this.

**Comment by lurch** [comment]
@pimterry Should this be closed too?

**Comment by pimterry** [comment]
Good spot, thanks! (More details in #834, if anybody else hits this)
